models:
  high:
    model: qwen3-max
    baseurl: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
    apikey: sk-
  middle:
    model: deepseek-chat
    baseurl: https://api.deepseek.com/chat/completions
    apikey: sk-
  default:
    model: glm-4.7
    baseurl: https://open.bigmodel.cn/api/paas/v4/chat/completions
    apikey: 1aab